"""Saves generated bakery demand reports to markdown files."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from bakery_analyst.reporting.charts import ChartBundle


def save_report(
    report_text: str,
    path: str = "report.md",
    chart_bundle: "ChartBundle | None" = None,
) -> None:
    """Write report_text to path, optionally appending inline base64 charts.

    Args:
        report_text: The report content to write.
        path: Destination file path. Defaults to 'report.md'.
        chart_bundle: Optional charts to embed as inline PNG images.
    """
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().isoformat()

    parts = [
        f"<!-- Generated by Bakery Demand Analyst — {timestamp} -->",
        "",
        report_text,
    ]

    if chart_bundle is not None:
        parts += [
            "",
            "---",
            "",
            "## Charts",
            "",
            f"### Forecast vs Actual — {chart_bundle.primary_shop_id} / {chart_bundle.primary_product_code}",
            "",
            f"![Forecast vs Actual](data:image/png;base64,{chart_bundle.forecast_vs_actual})",
        ]
        if chart_bundle.waste_stockout_bars is not None:
            parts += [
                "",
                "### Waste & Stockout Rates by Shop/Product",
                "",
                f"![Waste & Stockout Rates](data:image/png;base64,{chart_bundle.waste_stockout_bars})",
            ]
        if chart_bundle.temp_scatter is not None:
            parts += [
                "",
                f"### Temperature vs Sales — {chart_bundle.primary_shop_id} / {chart_bundle.primary_product_code}",
                "",
                f"![Temperature vs Sales](data:image/png;base64,{chart_bundle.temp_scatter})",
            ]

    content = "\n".join(parts) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
